name: linux-ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r dev-requirements.txt

      - name: Run tests
        run: inv t

  release:
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip3 install -r dev-requirements.txt

      - name: Run Release
        run: |
          git config --global user.email "bots@swellaby.com"
          git config --global user.name "Semantic Release Bot"
          semantic-release publish
        env:
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    